### ISSUE TITLE
Package for windows

### ISSUE THREAD

**Issue by HohMac** [arwesjs/arwes#13]
As I´m not familiar with GitHub and these packages I want to ask you if you can deploy a package useable for windows ?
A little documentation for production usage was already requested, so I don´t ask for that once again ;)
I´m looking forward to use the framework for some projects, keep on coding.

**Comment by romelperez** [comment]
Hi @HohMac !

Though I haven't tested it in Windows myself, it should work as it does in Unix systems (Linux / Mac).

But I plan to make some major refactors in the project soon and since the current release is alpha, the support may be limited.

It can take a while before the testing coverage is greater and the support is extended.

Thanks for using Arwes!
