### ISSUE TITLE
Can I use arwes in non-react project?

### ISSUE THREAD

**Issue by ReInventTheWheel** [arwesjs/arwes#16]
Great work! I cannot wait to utilize this project UI kit right away at the first sight of arwes. But as I went through the demo code, seems it's best used with reactjs? Is it possible to apply it in non-reactjs project? like vuejs or plain html files?

**Comment by romelperez** [comment]
Hi @ReInventTheWheel ! Thanks for trying out Arwes!

The project is still in alpha version, it means the support and extensibility is limited. In theory, you can execute Arwes in other tools system such as Vue. And since React can be used with plain JavaScript without any problem, you could do that with Arwes. But there isn't documentation on how to do it for now.

If you have any other question, feel free to ask.
