### ISSUE TITLE
Typo in Docs/index.md

### ISSUE THREAD

**Issue by njwest** [arwesjs/arwes#4]
Fixed by #3 

Line 35 is missing the word assets:

"Images and sounds are not provided, if you want to ***use the implemented in the docs***"

[pull request url](https://github.com/arwesjs/arwes/pull/3)

**Comment by romelperez** [comment]
Hi @njwest ! Thank you very much for your contribution! :)

**Comment by njwest** [comment]
My pleasure, me encanta Arwes!

I am currently working on an Arwes ReactJS frontend + Elixir/Phoenix backend :) Do you have any rough ideas re: Arwes form design?

Thank you for open-sourcing your great work!

**Comment by romelperez** [comment]
That's awesome @njwest !

There is plan on building Arwes form components definitely. But the idea is to standardize the main architecture for the base components first and define how they should interact with each other in animations and sounds. There are many more things. I am currently working on some changes which can't make public since they are still experimental. But I want to release some changes soon. :)

Keep in mind that it is still in alpha but any experience you have and any feedback you want to share, it will be very much welcome! :)

**Comment by njwest** [comment]
@romelperez Where is the best place to send feedback? Email, here, elsewhere? :)

**Comment by romelperez** [comment]
@njwest It can be here! Create issues with your ideas. I'd love you read them! :D

Thank you very much for your enthusiasm!
