### ISSUE TITLE
Error during install with node v10.0.0

### ISSUE THREAD

**Issue by ReactGirl** [arwesjs/arwes#6]
Error:
(node:11834) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by romelperez** [comment]
Hi @ReactGirl ! Thanks for try out Arwes!

![screenshot from 2018-07-07 16 15 45](https://user-images.githubusercontent.com/1393135/42414729-2242487c-8201-11e8-8b1e-7f9d4b157649.png)

I think it is because of another package [upath](https://www.npmjs.com/package/upath) version 1.0.4, it seems that only works with node version greater than 4 and less than 9.

If you have any other question, feel free to ask.

**Comment by ReactGirl** [comment]
Yes! It was my bad. Thanks.

**Comment by romelperez** [comment]
You are welcome! Feel free to ask any question or give any recommendation ;)
